### ISSUE TITLE
UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by hgscott** [Devlin-Moyer/macaw#1]
I was testing out MACAW on my own machine, and got error.

Here's a screenshot of what I ran/got:
![image](https://github.com/Devlin-Moyer/macaw/assets/40765908/7aabc5c6-68a1-438a-b379-3ba48456f820)

This is the line that the error references:
https://github.com/Devlin-Moyer/macaw/blob/f91e2dd60360901e3fb925d016ac7ecf30f31937/macaw_structural.py#L414

It looks like the `model` variable isn't defined until line 420.

**Comment by Devlin-Moyer** [comment]
ah yep I fell for the classic blunder of not testing everything with no input to make sure all the code for telling you that you didn't provide the right input that I remembered to write actually worked. I just fixed that

**Comment by hgscott** [comment]
That resolved it, thanks!
