### ISSUE TITLE
Results not added to Dataframe

### ISSUE THREAD

**Issue by hgscott** [Devlin-Moyer/macaw#2]
When I run the E. coli model as shown in the readme, all the tests run, but nothing seems to be added to the test_results data frame. 

![image](https://github.com/Devlin-Moyer/macaw/assets/40765908/fcaf7967-e601-4eb7-8744-e49930de96ae)

**Comment by Devlin-Moyer** [comment]
fascinating that the edge list DataFrame appears to be totally intact; I will investigate

**Comment by Devlin-Moyer** [comment]
anyway in the meantime if you import the specific test functions independently, those should work, because I have scripts running right now calling them that way (instead of using `run_all_tests()`) that are not having this problem

**Comment by Devlin-Moyer** [comment]
ah it was a problem with how `run_all_tests` called `loop_test`; I added the `corr_thresh` argument to `loop_test` somewhat recently and forgot to update `run_all_tests` accordingly, so it wound up calling `loop_test` with `add_suffixes = True` even if it was False for every other test, so the `reaction_equation` columns never matched, so the merges failed. Anyway it's fixed now

**Comment by hgscott** [comment]
Thanks! I was able to run everything on my machine!
